# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               anayjoshi
tagline:             '.com'
description:         'A textual representation of pop-ups in my volatile memory'
url:                 http://anayjoshi.com
baseurl:             /
paginate:            100

# About/contact
author:
  name:              Anaykumar Joshi
  url:               https://twitter.com/sudo
  email:             anaykumar.joshi@gmail.com
