# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               AKJ
tagline:             'web presence'
description:         'A blog dominated by technology'
url:                 http://anayjoshi.com
baseurl:             /
paginate:            100

# About/contact
author:
  name:              Anaykumar Joshi
  url:               https://twitter.com/AnaykumarJoshi
  email:             anaykumar.joshi@gmail.com
