# Dependencies
markdown:            kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               anayjoshi
tagline:             '.com'
description:         'A textual representation of pop-ups in my volatile memory'
url:                 http://anayjoshi.com
production_url:      http://anayjoshi.com
baseurl:             /
paginate:            100

# About/contact
author:
  name:              Anaykumar Joshi
  twitter:           https://twitter.com/AnaykumarJoshi
  email:             anaykumar.joshi@gmail.com
